# Generated by Django 4.2.5 on 2023-10-11 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LolTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('postion', models.CharField(choices=[('TP', 'Top'), ('JG', 'Jungle'), ('MD', 'Mid'), ('AD', 'ADC'), ('SP', 'Support')], max_length=2)),
                ('lol_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='league.lolteam')),
            ],
        ),
    ]
