# Generated by Django 4.2.5 on 2023-10-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_team_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.CharField(max_length=30)),
                ('deaths', models.CharField(max_length=30)),
                ('assists', models.CharField(max_length=30)),
                ('turrets', models.CharField(max_length=30)),
                ('inhibitors', models.CharField(max_length=30)),
                ('dragonKills', models.CharField(max_length=30)),
                ('baronKills', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='player',
            old_name='postion',
            new_name='position',
        ),
    ]
